export const postList = [
    {
        id: '1',
        title: 'Selamat datang di blog saya',
        category: 'Panduan',
        topic: 'Selamat datang',
        short: 'Ini merupakan halaman blog saya pribadi jadi...',
        img: 'https://source.unsplash.com/1000x800?Happy',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '2',
        title: 'Cara menjadi penguasa dunia',
        category: 'Tutorial',
        topic: 'Politik',
        short: 'Kali ini saya akan membagikan tutorial menguasai dunia...',
        img: 'https://source.unsplash.com/1000x800?politic',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Cara berenang menyeberangi samudra atlantik',
        category: 'Tutorial',
        topic: 'Skill',
        short: 'Seberapa effortkah anda dengan pasangan anda...',
        img: 'https://source.unsplash.com/1000x800?atlantic',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Cara menyelami palung mariana',
        category: 'Tutorial',
        topic: 'Skill',
        short: 'Jelajahi misteri yang belum anda dan semua orang ketahui...',
        img: 'https://source.unsplash.com/1000x800?shark',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Bertapa untuk mendapatkan kekuataun untuk bisa terbang',
        category: 'Heboh',
        topic: 'Mistik',
        short: 'Heboh seorang petapa genit sedang melakukan uji coba jutsu...',
        img: 'https://source.unsplash.com/1000x800?wizard',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Membangun peradaban maju untuk masa depan',
        category: 'pandangan',
        topic: 'sejarah',
        short: 'Setiap masa ada peradaban tertinggi yang menguasainya...',
        img: 'https://source.unsplash.com/1000x800?kingdom',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '2',
        title: 'Cara menjadi penguasa dunia',
        category: 'Tutorial',
        topic: 'Politik',
        short: 'Kali ini saya akan membagikan tutorial menguasai dunia...',
        img: 'https://source.unsplash.com/1000x800?politic',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Cara berenang menyeberangi samudra atlantik',
        category: 'Tutorial',
        topic: 'Skill',
        short: 'Seberapa effortkah anda dengan pasangan anda...',
        img: 'https://source.unsplash.com/1000x800?atlantic',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Cara menyelami palung mariana',
        category: 'Tutorial',
        topic: 'Skill',
        short: 'Jelajahi misteri yang belum anda dan semua orang ketahui...',
        img: 'https://source.unsplash.com/1000x800?shark',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Bertapa untuk mendapatkan kekuataun untuk bisa terbang',
        category: 'Heboh',
        topic: 'Mistik',
        short: 'Heboh seorang petapa genit sedang melakukan uji coba jutsu...',
        img: 'https://source.unsplash.com/1000x800?wizard',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Membangun peradaban maju untuk masa depan',
        category: 'pandangan',
        topic: 'sejarah',
        short: 'Setiap masa ada peradaban tertinggi yang menguasainya...',
        img: 'https://source.unsplash.com/1000x800?kingdom',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '2',
        title: 'Cara menjadi penguasa dunia',
        category: 'Tutorial',
        topic: 'Politik',
        short: 'Kali ini saya akan membagikan tutorial menguasai dunia...',
        img: 'https://source.unsplash.com/1000x800?politic',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Cara berenang menyeberangi samudra atlantik',
        category: 'Tutorial',
        topic: 'Skill',
        short: 'Seberapa effortkah anda dengan pasangan anda...',
        img: 'https://source.unsplash.com/1000x800?atlantic',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Cara menyelami palung mariana',
        category: 'Tutorial',
        topic: 'Skill',
        short: 'Jelajahi misteri yang belum anda dan semua orang ketahui...',
        img: 'https://source.unsplash.com/1000x800?shark',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Bertapa untuk mendapatkan kekuataun untuk bisa terbang',
        category: 'Heboh',
        topic: 'Mistik',
        short: 'Heboh seorang petapa genit sedang melakukan uji coba jutsu...',
        img: 'https://source.unsplash.com/1000x800?wizard',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Membangun peradaban maju untuk masa depan',
        category: 'pandangan',
        topic: 'sejarah',
        short: 'Setiap masa ada peradaban tertinggi yang menguasainya...',
        img: 'https://source.unsplash.com/1000x800?kingdom',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '2',
        title: 'Cara menjadi penguasa dunia',
        category: 'Tutorial',
        topic: 'Politik',
        short: 'Kali ini saya akan membagikan tutorial menguasai dunia...',
        img: 'https://source.unsplash.com/1000x800?politic',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Cara berenang menyeberangi samudra atlantik',
        category: 'Tutorial',
        topic: 'Skill',
        short: 'Seberapa effortkah anda dengan pasangan anda...',
        img: 'https://source.unsplash.com/1000x800?atlantic',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Cara menyelami palung mariana',
        category: 'Tutorial',
        topic: 'Skill',
        short: 'Jelajahi misteri yang belum anda dan semua orang ketahui...',
        img: 'https://source.unsplash.com/1000x800?shark',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Bertapa untuk mendapatkan kekuataun untuk bisa terbang',
        category: 'Heboh',
        topic: 'Mistik',
        short: 'Heboh seorang petapa genit sedang melakukan uji coba jutsu...',
        img: 'https://source.unsplash.com/1000x800?wizard',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Membangun peradaban maju untuk masa depan',
        category: 'pandangan',
        topic: 'sejarah',
        short: 'Setiap masa ada peradaban tertinggi yang menguasainya...',
        img: 'https://source.unsplash.com/1000x800?kingdom',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '2',
        title: 'Cara menjadi penguasa dunia',
        category: 'Tutorial',
        topic: 'Politik',
        short: 'Kali ini saya akan membagikan tutorial menguasai dunia...',
        img: 'https://source.unsplash.com/1000x800?politic',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Cara berenang menyeberangi samudra atlantik',
        category: 'Tutorial',
        topic: 'Skill',
        short: 'Seberapa effortkah anda dengan pasangan anda...',
        img: 'https://source.unsplash.com/1000x800?atlantic',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Cara menyelami palung mariana',
        category: 'Tutorial',
        topic: 'Skill',
        short: 'Jelajahi misteri yang belum anda dan semua orang ketahui...',
        img: 'https://source.unsplash.com/1000x800?shark',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Bertapa untuk mendapatkan kekuataun untuk bisa terbang',
        category: 'Heboh',
        topic: 'Mistik',
        short: 'Heboh seorang petapa genit sedang melakukan uji coba jutsu...',
        img: 'https://source.unsplash.com/1000x800?wizard',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
    {
        id: '3',
        title: 'Membangun peradaban maju untuk masa depan',
        category: 'pandangan',
        topic: 'sejarah',
        short: 'Setiap masa ada peradaban tertinggi yang menguasainya...',
        img: 'https://source.unsplash.com/1000x800?kingdom',
        date: '1 dec 2023',
        status: 'live',
        version: '1'
    },
]